## Section 3: Fundamentals of Python
### Lists, [ ] Brackets, Slicing, Tuples, Functions, Packages, Numpy and Arrays, Slicing Arrays

---

### Lists

In [1]:
#Lists in Python are like vectors in R
#list - ordered sequence of elements starting at element 0

In [2]:
#Mixed data types - can have mixed data types in a single list....compared to vectors in R, which have to be the same data type

In [3]:
MyFirstList = [3, 45, 56, 732]     #notice that lists use square brackets [ ]

In [4]:
type(MyFirstList)

list

In [5]:
l2 = ["hello", 24, True, 55.3]

In [6]:
l2

['hello', 24, True, 55.3]

In [7]:
#lists can contain a list as part of its elements

In [10]:
l3 = ['how are you?', 55, MyFirstList]

In [11]:
l3

['how are you?', 55, [3, 45, 56, 732]]

---

#### Range()

In [12]:
range(15)         #Python 3 - this is the same as xrange() in Python 2

range(0, 15)

In [13]:
list(range(15))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [14]:
[1,2,3,4,5,6,7]

[1, 2, 3, 4, 5, 6, 7]

In [15]:
x = [1,2,3,4,5,6,7]
x

[1, 2, 3, 4, 5, 6, 7]

In [16]:
list(range(8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [18]:
z = list(range(1, 8))    #start at 1, end at 8 (does not include 8)
z

[1, 2, 3, 4, 5, 6, 7]

In [20]:
z2 = list(range(100, 121))
z2

[100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120]

In [21]:
w = list(range(100, 111, 2))   #last number tells what increment the list should go by
w

[100, 102, 104, 106, 108, 110]

In [22]:
w2 = list(range(100, 201, 10))   #last number tells what increment the list should go by
w2

[100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]

---


### [ ] Brackets

In [2]:
w = ['a', 'b', 'c', 'd',' e']
w

['a', 'b', 'c', 'd', ' e']

In [3]:
w[0]      #use [ ] to index (call) an element in your list

'a'

In [4]:
w[1]

'b'

In [5]:
w[2]

'c'

In [6]:
#use len() operator to find out how many elements are in a list

In [7]:
len(w)   #asking how many total elements are in list w

5

In [8]:
#while it says there are 5 elements in list w, the last element is the total number of elements - 1 (aka 5-1)
w[4]       #this will call the last element in the list

' e'

In [9]:
w

['a', 'b', 'c', 'd', ' e']

In [10]:
#so this list is indexed as:
# a    b    c    d      e
# 0    1    2    3      4  

In [11]:
#another way: use negative indexation
#negative indexation starts with the last element as -1
#  a    b    c    d      e        #list w
#  0    1    2    3      4        #indexation
# -5   -4   -3   -2     -1        #negative indexation

In [12]:
w[-1]   #different behavior to R; this code in R would exclude the first element

' e'

In [13]:
w[-3]

'c'

In [14]:
#w[-3] AKA
w[2]

'c'

In [15]:
#overwrite values:

In [16]:
w

['a', 'b', 'c', 'd', ' e']

In [17]:
w[2] = 63

In [18]:
w

['a', 'b', 63, 'd', ' e']

In [19]:
#what happens if you try to call an element beyond the list?
w[15]

IndexError: list index out of range

In [20]:
w[-7]

IndexError: list index out of range

In [21]:
MyFavoriteList = [1,2,3,4,87]
MyFavoriteList

[1, 2, 3, 4, 87]

In [22]:
d = [99, 38, 'm', MyFavoriteList, 12]
d

[99, 38, 'm', [1, 2, 3, 4, 87], 12]

In [23]:
len(d)

5

In [24]:
d[4]

12

In [25]:
d[3]

[1, 2, 3, 4, 87]

In [26]:
#lygometry Ted Talk by Amin Toufani https://www.youtube.com/watch?v=nwRJLa0igmQ

---

### Slicing Lists

In [ ]:
# Slicing takes a subset out of your list (aka subsetting in R)

In [28]:
#Imagine a list:
# 'A'  'B'  'C'  'D'  'E'  'F'  'G'  'H'  'I'  'J'
#  0    1    2    3    4    5    6    7    8    9
# -10  -9   -8   -7   -6   -5   -4   -3   -2   -1          negative indexation
# 2:7 would call/extract 'C' through 'G' - so it starts at the element 2 ('C') and ends at 7 (NOT including 7) so 6 or 'G'
# 2:7 aka -8:-3

In [29]:
#Advanced Slicing
#  : :         two colons allow you to have three spots
# 2:9:2       #third number identifies the step (default is 1)

In [30]:
letters = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']
letters

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [31]:
letters[:]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [32]:
letters[ : ]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [33]:
letters[2:]   #start at 2

['C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [34]:
letters[:7]   #end at 7 (not inclusive)

['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [35]:
letters[2:7]

['C', 'D', 'E', 'F', 'G']

In [36]:
letters[-8:7]      #combines indexation and negative indexation

['C', 'D', 'E', 'F', 'G']

In [37]:
letters[-8:-3]

['C', 'D', 'E', 'F', 'G']

---

#### Advanced Slicing

In [39]:
letters[2:9]

['C', 'D', 'E', 'F', 'G', 'H', 'I']

In [40]:
letters[2:9:2]      #third number indicates the step

['C', 'E', 'G', 'I']

In [41]:
letters

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [42]:
letters[::3]

['A', 'D', 'G', 'J']

In [43]:
letters[::-2]    #negative step will list in the output in reverse order

['J', 'H', 'F', 'D', 'B']

In [44]:
letters[::-1]

['J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']

---

##### Negative steps

In [47]:
letters[::-1]

['J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']

In [48]:
letters[2:7]

['C', 'D', 'E', 'F', 'G']

In [51]:
letters[2:7:-1]

[]

In [52]:
letters[6:1:-1]    #if you use a negative step, you have to reverse order the numbers you're looking for

['G', 'F', 'E', 'D', 'C']

In [53]:
letters[6:1:-2]

['G', 'E', 'C']

----

### Tuples in Python

In [55]:
#tuple = immutable list or immutable sequence of values

In [57]:
t1 = (345, 674, 934)         #looks like a list, but with ( )

In [58]:
t1

(345, 674, 934)

In [59]:
t1[0]

345

In [60]:
t1[1]

674

In [61]:
t1[1] = 45

TypeError: 'tuple' object does not support item assignment

In [62]:
#tuples CANNOT be changed

---

### Functions

In [64]:
range(20,31)

range(20, 31)

In [65]:
list(range(20,31))

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [66]:
mylist1 = list(range(20,31))

In [67]:
mylist1

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [68]:
print(mylist1)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


In [69]:
len(mylist1)

11

In [70]:
type(mylist1)

list

In [71]:
max(mylist1)

30

In [72]:
min(mylist1)

20

In [73]:
max(11,435,7)

435

----

### Packages

In [75]:
# Module - a module is simply a file containing Python definitions, functions, and statements. Putting code into modules is useful because of the ability to import the module functionality into your script of IPython session.

In [76]:
# Package - a package is just a way of collecting related modules together within a single tree-like hierarchy. Very complex packages like NumPy or SciPy have hundreds of individual modules so putting them into a directory-like structure keeps things organized and avoids name collisions.

In [77]:
# Step 1: Find the Package

In [78]:
#best place to find a package is Github

In [79]:
# Step 2: Install

In [80]:
#install using anaconda command prompt
#type in: conda instal PACKAGENAME
#OR
#type in: pip install PACKAGENAME

In [81]:
# Step 3: Import

In [82]:
# import PACKAGENAME
#ex: import scrapy

In [1]:
#or import just a function from the package:
# from scrapy.crawler import CrawlerProcess

In [2]:
import scrapy

In [3]:
from scrapy.crawler import CrawlerProcess

In [4]:
import numpy

---

### NumPy and Arrays

In [6]:
l = [23245, 27, 546, 215, -1234]

In [7]:
l

[23245, 27, 546, 215, -1234]

In [8]:
#lists are very similar to arrays in other programming languages like C++ and similar to vectors in R

In [9]:
#2 types of arrays in Python:
#array array - built into the core of Python
#numpy array - numpy is a package that you can install, included in most of your code and research; much more versatile with array arrays

In [10]:
import numpy as np

In [11]:
np.array(l)     #will convert list to an array

array([23245,    27,   546,   215, -1234])

In [12]:
# Lists vs. Arrays:
#1) arrays cannot have different data types (lists can)
#2) arrays have more methods (tab options) than lists
#3) arrays are needed when working with matrices, tables, etc. for data anlyses

In [13]:
a = np.array(l)

In [14]:
a

array([23245,    27,   546,   215, -1234])

In [15]:
b = np.array([12, 455, 63.3, True, 'a'])

In [16]:
b           #notice that all elements in the array were converted to strings because arrays cannot have more than one data type

array(['12', '455', '63.3', 'True', 'a'], dtype='<U32')

In [17]:
l.pop()         #lists have prestored information with them in python - use the tab key to access the options

-1234

In [18]:
#more methods available for arrays than for lists!

In [19]:
a.mean()

4559.8

---

### Slicing Arrays

In [22]:
l

[23245, 27, 546, 215]

In [23]:
l[1:]

[27, 546, 215]

In [24]:
l[0:2]

[23245, 27]

In [25]:
l[::2]

[23245, 546]

In [26]:
a

array([23245,    27,   546,   215, -1234])

In [27]:
a[2:]

array([  546,   215, -1234])

In [28]:
a[2:4]

array([546, 215])

In [29]:
#whenever you slice an array, you do not create a copy of that array. When you slice lists, you DO create another copy of that list.

In [30]:
b = a[2:4]

In [31]:
b

array([546, 215])

In [32]:
b[0]

546

In [33]:
b[:] = 111

In [34]:
b

array([111, 111])

In [35]:
a

array([23245,    27,   111,   111, -1234])

In [36]:
#notice that the values have been replaced in the original array

In [38]:
c = a.copy()         #make a copy of the original array (a) to change c

In [40]:
c

array([23245,    27,   111,   111, -1234])

In [41]:
a

array([23245,    27,   111,   111, -1234])

In [ ]:
#Slicing a list creates a copy of that list
#Slicing an array creates a view of that array (not a copy)